packages:
  - packages/*
  - plugins/*
  - sandbox


catalog:
  zod: 4.3.5

catalogs:
  payload-stack:
    '@payloadcms/db-postgres': 3.72.0
    '@payloadcms/next': 3.72.0
    '@payloadcms/richtext-lexical': 3.72.0
    '@payloadcms/ui': 3.72.0
    '@types/react': 19.2.1
    '@types/react-dom': 19.2.1
    next: 15.5.9
    payload: 3.72.0
    react: 19.2.1
    react-dom: 19.2.1
    typescript: 5.7.3
  vite:
    vite: 7.0.6

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp
