// Generated by ts-to-zod
import { z } from 'zod';

export const supportedTimezonesSchema = z.union([
  z.literal('Pacific/Midway'),
  z.literal('Pacific/Niue'),
  z.literal('Pacific/Honolulu'),
  z.literal('Pacific/Rarotonga'),
  z.literal('America/Anchorage'),
  z.literal('Pacific/Gambier'),
  z.literal('America/Los_Angeles'),
  z.literal('America/Tijuana'),
  z.literal('America/Denver'),
  z.literal('America/Phoenix'),
  z.literal('America/Chicago'),
  z.literal('America/Guatemala'),
  z.literal('America/New_York'),
  z.literal('America/Bogota'),
  z.literal('America/Caracas'),
  z.literal('America/Santiago'),
  z.literal('America/Buenos_Aires'),
  z.literal('America/Sao_Paulo'),
  z.literal('Atlantic/South_Georgia'),
  z.literal('Atlantic/Azores'),
  z.literal('Atlantic/Cape_Verde'),
  z.literal('Europe/London'),
  z.literal('Europe/Berlin'),
  z.literal('Africa/Lagos'),
  z.literal('Europe/Athens'),
  z.literal('Africa/Cairo'),
  z.literal('Europe/Moscow'),
  z.literal('Asia/Riyadh'),
  z.literal('Asia/Dubai'),
  z.literal('Asia/Baku'),
  z.literal('Asia/Karachi'),
  z.literal('Asia/Tashkent'),
  z.literal('Asia/Calcutta'),
  z.literal('Asia/Dhaka'),
  z.literal('Asia/Almaty'),
  z.literal('Asia/Jakarta'),
  z.literal('Asia/Bangkok'),
  z.literal('Asia/Shanghai'),
  z.literal('Asia/Singapore'),
  z.literal('Asia/Tokyo'),
  z.literal('Asia/Seoul'),
  z.literal('Australia/Brisbane'),
  z.literal('Australia/Sydney'),
  z.literal('Pacific/Guam'),
  z.literal('Pacific/Noumea'),
  z.literal('Pacific/Auckland'),
  z.literal('Pacific/Fiji'),
]);

export const userAuthOperationsSchema = z.object({
  forgotPassword: z.object({
    email: z.string(),
    password: z.string(),
  }),
  login: z.object({
    email: z.string(),
    password: z.string(),
  }),
  registerFirstUser: z.object({
    email: z.string(),
    password: z.string(),
  }),
  unlock: z.object({
    email: z.string(),
    password: z.string(),
  }),
});

export const userSchema = z.object({
  id: z.string(),
  notificationPreferences: z
    .object({
      emailEnabled: z.boolean().optional().nullable(),
    })
    .optional(),
  updatedAt: z.string(),
  createdAt: z.string(),
  email: z.string(),
  resetPasswordToken: z.string().optional().nullable(),
  resetPasswordExpiration: z.string().optional().nullable(),
  salt: z.string().optional().nullable(),
  hash: z.string().optional().nullable(),
  loginAttempts: z.number().optional().nullable(),
  lockUntil: z.string().optional().nullable(),
  sessions: z
    .array(
      z.object({
        id: z.string(),
        createdAt: z.string().optional().nullable(),
        expiresAt: z.string(),
      }),
    )
    .optional()
    .nullable(),
  password: z.string().optional().nullable(),
});

export const uploadSchema = z.object({
  id: z.string(),
  updatedAt: z.string(),
  createdAt: z.string(),
  url: z.string().optional().nullable(),
  thumbnailURL: z.string().optional().nullable(),
  filename: z.string().optional().nullable(),
  mimeType: z.string().optional().nullable(),
  filesize: z.number().optional().nullable(),
  width: z.number().optional().nullable(),
  height: z.number().optional().nullable(),
  focalX: z.number().optional().nullable(),
  focalY: z.number().optional().nullable(),
});

export const notificationSchema = z.object({
  id: z.string(),
  recipient: z.union([z.string(), userSchema]),
  event: z.string(),
  actor: z.union([z.string().nullable(), userSchema]).optional(),
  message: z.union([
    z.object({
      type: z.literal('static'),
      value: z.string(),
    }),
    z.object({
      type: z.literal('live'),
      parts: z.array(
        z.union([
          z.string(),
          z.object({
            type: z.union([
              z.literal('actor'),
              z.literal('document'),
              z.literal('meta'),
            ]),
            field: z.string(),
          }),
        ]),
      ),
    }),
  ]),
  url: z.string().optional().nullable(),
  meta: z
    .union([
      z.record(z.string(), z.unknown()),
      z.array(z.unknown()),
      z.string(),
      z.number(),
      z.boolean(),
    ])
    .optional()
    .nullable(),
  documentReference: z
    .object({
      entity: z
        .union([z.literal('collection'), z.literal('global')])
        .optional()
        .nullable(),
      slug: z.string().optional().nullable(),
      documentId: z.string().optional().nullable(),
    })
    .optional(),
  readAt: z.string().optional().nullable(),
  emailSentAt: z.string().optional().nullable(),
  emailError: z.string().optional().nullable(),
  updatedAt: z.string(),
  createdAt: z.string(),
});

export const subscriptionSchema = z.object({
  id: z.string(),
  user: z.union([z.string(), userSchema]),
  documentReference: z.object({
    entity: z.union([z.literal('collection'), z.literal('global')]),
    slug: z.string(),
    documentId: z.string().optional().nullable(),
  }),
  updatedAt: z.string(),
  createdAt: z.string(),
});

export const payloadKvSchema = z.object({
  id: z.string(),
  key: z.string(),
  data: z
    .union([
      z.record(z.string(), z.unknown()),
      z.array(z.unknown()),
      z.string(),
      z.number(),
      z.boolean(),
    ])
    .nullable(),
});

export const payloadLockedDocumentSchema = z.object({
  id: z.string(),
  document: z
    .union([
      z
        .object({
          relationTo: z.literal('users'),
          value: z.union([z.string(), userSchema]),
        })
        .nullable(),
      z
        .object({
          relationTo: z.literal('uploads'),
          value: z.union([z.string(), uploadSchema]),
        })
        .nullable(),
      z
        .object({
          relationTo: z.literal('notifications'),
          value: z.union([z.string(), notificationSchema]),
        })
        .nullable(),
      z
        .object({
          relationTo: z.literal('subscriptions'),
          value: z.union([z.string(), subscriptionSchema]),
        })
        .nullable(),
    ])
    .optional(),
  globalSlug: z.string().optional().nullable(),
  user: z.object({
    relationTo: z.literal('users'),
    value: z.union([z.string(), userSchema]),
  }),
  updatedAt: z.string(),
  createdAt: z.string(),
});

export const payloadPreferenceSchema = z.object({
  id: z.string(),
  user: z.object({
    relationTo: z.literal('users'),
    value: z.union([z.string(), userSchema]),
  }),
  key: z.string().optional().nullable(),
  value: z
    .union([
      z.record(z.string(), z.unknown()),
      z.array(z.unknown()),
      z.string(),
      z.number(),
      z.boolean(),
    ])
    .optional()
    .nullable(),
  updatedAt: z.string(),
  createdAt: z.string(),
});

export const payloadMigrationSchema = z.object({
  id: z.string(),
  name: z.string().optional().nullable(),
  batch: z.number().optional().nullable(),
  updatedAt: z.string(),
  createdAt: z.string(),
});

export const authSchema = z.record(z.string(), z.unknown());
